version: '3'

services:

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: db
      DB_USER: postgres
      DB_PASSWORD: postgres