version: '3'

services:

  db:
    image: postgres:alpine
    ports:
      - "5433:5433"
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: db
    command: -p 5433

  datadog:
    image: datadog/agent
    container_name: "datadog-dev-env"
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=us5.datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro


  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DB_HOST: db
      DB_PORT: 5433
      DB_NAME: db
      DB_USER: postgres
      DB_PASSWORD: postgres

    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "manager-api-dev", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'
