version: '3'

services:
  snippet-share-api:
    container_name: "snippet-sharer-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      DB_USER: sa
      DB_PASSWORD: password
      DB_NAME: compose-db
      DB_HOST: snippet_sharer_db
      DB_PORT: 5432

  snippet_share_db:
    container_name: snippet_sharer_db
    image: postgres:12
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: compose-db